services:
    iim.blog.admin.article:
      class: iim\BlogBundle\Admin\CommentAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Blog, label: Comments}
      arguments: [null, iim\BlogBundle\Entity\Comment,SonataAdminBundle:CRUD]